#ifndef PROGRAM_STATE_H_INCLUDED
#define PROGRAM_STATE_H_INCLUDED


enum ProgramState
{
    PROGRAM_NOT_RUNNING,
    PROGRAM_RUNNING,
    PROGRAM_PAUSED,
    PROGRAM_SUSPENDED,
    PROGRAM_FINISHED
};



#endif // PROGRAM_STATE_H_INCLUDED
